name: CI/CD для Todo приложения

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      BACKEND_IMAGE: ${{ secrets.DOCKER_USERNAME }}/todo-backend:latest
      FRONTEND_IMAGE: ${{ secrets.DOCKER_USERNAME }}/todo-frontend:latest
      DATABASE_IMAGE: ${{ secrets.DOCKER_USERNAME }}/todo-database:latest
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
    
    steps:
      - uses: actions/checkout@v3
      
      # Создание .env файла для бэкенда
      - name: Создание .env файла
        run: |
          echo "DATABASE_URL=postgresql://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@todo-db:5432/${{ secrets.DB_NAME }}" > backend/.env
      
      # Создание сети
      - name: Создание Docker сети
        run: docker network create todo-network
      
      # Сборка образа базы данных
      - name: Сборка образа базы данных
        run: |
          docker build -t $DATABASE_IMAGE \
            --build-arg POSTGRES_USER=${{ secrets.DB_USER }} \
            --build-arg POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }} \
            --build-arg POSTGRES_DB=${{ secrets.DB_NAME }} \
            ./database
      
      # Запуск контейнера базы данных
      - name: Запуск контейнера базы данных
        run: |
          docker run -d \
            --name todo-db \
            --network todo-network \
            -p 5432:5432 \
            -e POSTGRES_USER=${{ secrets.DB_USER }} \
            -e POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e POSTGRES_DB=${{ secrets.DB_NAME }} \
            $DATABASE_IMAGE
          
          # Ждем 5 секунд, пока БД полностью запустится
          sleep 5
      
      # Сборка образа бэкенда
      - name: Сборка образа бэкенда
        run: docker build -t $BACKEND_IMAGE ./backend
      
      # Запуск контейнера бэкенда
      - name: Запуск контейнера бэкенда
        run: |
          docker run -d \
            --name todo-backend \
            --network todo-network \
            -p 8000:8000 \
            -e DATABASE_URL=postgresql://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@todo-db:5432/${{ secrets.DB_NAME }} \
            -e EMAIL_HOST=${{ secrets.EMAIL_HOST }} \
            -e EMAIL_PORT=${{ secrets.EMAIL_PORT }} \
            -e EMAIL_USER=${{ secrets.EMAIL_USER }} \
            -e EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }} \
            -e EMAIL_FROM=${{ secrets.EMAIL_FROM }} \
            -e IMAP_HOST=${{ secrets.IMAP_HOST }} \
            -e IMAP_PORT=${{ secrets.IMAP_PORT }} \
            -e IMAP_USER=${{ secrets.IMAP_USER }} \
            -e IMAP_PASSWORD=${{ secrets.IMAP_PASSWORD }} \
            -e POP3_HOST=${{ secrets.POP3_HOST }} \
            -e POP3_PORT=${{ secrets.POP3_PORT }} \
            -e POP3_USER=${{ secrets.POP3_USER }} \
            -e POP3_PASSWORD=${{ secrets.POP3_PASSWORD }} \
            -e WEBSOCKET_PORT=8000 \
            $BACKEND_IMAGE
          
          # Ждем 5 секунд, пока бэкенд полностью запустится
          sleep 5
      
      # Сборка образа фронтенда
      - name: Сборка образа фронтенда
        run: docker build -t $FRONTEND_IMAGE ./frontend
      
      # Запуск контейнера фронтенда
      - name: Запуск контейнера фронтенда
        run: |
          docker run -d \
            --name todo-frontend \
            --network todo-network \
            -p 3000:3000 \
            -e REACT_APP_API_URL=http://todo-backend:8000 \
            $FRONTEND_IMAGE
          
          # Ждем 10 секунд, пока фронтенд полностью запустится
          sleep 10
      
      # Проверка доступности бэкенда
      - name: Проверка доступности бэкенда
        run: |
          curl -s -f http://localhost:8000/api/health || exit 1
          curl -s -f http://localhost:8000/tasks || exit 1
          echo "Бэкенд работает корректно"
      
      # Проверка доступности фронтенда (обычно просто проверяем, что страница загружается)
      - name: Проверка доступности фронтенда
        run: |
          curl -s -f http://localhost:3000 || exit 1
          echo "Фронтенд работает корректно"
      
      # Авторизация в Docker Hub
      - name: Авторизация в Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # Отправка образов в Docker Hub
      - name: Отправка образов в Docker Hub
        run: |
          docker push $BACKEND_IMAGE
          docker push $FRONTEND_IMAGE
          docker push $DATABASE_IMAGE
      
      # Очистка контейнеров
      - name: Очистка контейнеров
        if: always()
        run: |
          docker stop todo-frontend todo-backend todo-db || true
          docker rm todo-frontend todo-backend todo-db || true
      
      # Очистка сети
      - name: Очистка сети
        if: always()
        run: docker network rm todo-network || true 